//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Resouces
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resouces()
        {
            this.Collection = new HashSet<Collection>();
            this.Comment = new HashSet<Comment>();
        }
        [Display(Name = "编号")]
        public int ResoucesID { get; set; }
        [Display(Name = "发布者ID")]
        public Nullable<int> UserID { get; set; }
        [Display(Name = "链接ID")]
        public Nullable<int> LinkID { get; set; }
        [Display(Name = "图片ID")]
        public Nullable<int> PictureID { get; set; }
        [Display(Name = "类别ID")]
        public Nullable<int> CategoryID { get; set; }
        [Display(Name = "标签ID")]
        public Nullable<int> LableID { get; set; }
        [Display(Name = "发布时间")]
        public System.DateTime Releasetime { get; set; }
        [Display(Name = "资源名称")]
        public string Rname { get; set; }
        [Display(Name = "资源描述")]
        public string Rdescribe { get; set; }
        [Display(Name = "获取需求")]
        public Nullable<int> Rdemand { get; set; }
        [Display(Name = "资源状态")]
        public Nullable<int> Rstate { get; set; }
        [Display(Name = "已有阅览量")]
        public int Reading { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Lable Lable { get; set; }
        public virtual Link Link { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
