//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserID { get; set; }
        public System.DateTime RegistrationTime { get; set; }
        public int IntegralID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public Nullable<int> ResoucesID { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public string E_mail { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserState { get; set; }
    
        public virtual Integral Integral { get; set; }
        public virtual Record Record { get; set; }
        public virtual Resouces Resouces { get; set; }
    }
}
