//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.Collection = new HashSet<Collection>();
            this.Comment = new HashSet<Comment>();
            this.Resouces = new HashSet<Resouces>();
        }
        [Display(Name ="编号")]
        public int UserID { get; set; }
        [Display(Name = "注册时间")]
        public System.DateTime RegistrationTime { get; set; }
        [Display(Name = "登录名")]
        public string LoginName { get; set; }
        [Display(Name = "登录密码")]
        public string LoginPwd { get; set; }
        [Display(Name = "邮箱")]
        public string E_mail { get; set; }
        [Display(Name = "用户名")]
        public string UserName { get; set; }
        [Display(Name = "性别")]
        public string UserSex { get; set; }
        [Display(Name = "签名")]
        public string Userdescribe { get; set; }
        [Display(Name = "拥有积分")]
        public int integral { get; set; }
        [Display(Name = "状态")]
        public int UserState { get; set; }
        [Display(Name = "头像")]
        public string UserPicture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resouces> Resouces { get; set; }
    }
}
