//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.Comment = new HashSet<Comment>();
            this.Resouces = new HashSet<Resouces>();
            this.Collection = new HashSet<Collection>();
        }
    
        public int UserID { get; set; }
        public System.DateTime RegistrationTime { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public string E_mail { get; set; }
        public string UserName { get; set; }
        public string UserSex { get; set; }
        public string Userdescribe { get; set; }
        public Nullable<int> integral { get; set; }
        public Nullable<int> UserState { get; set; }
        public string UserPicture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resouces> Resouces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collection { get; set; }
    }
}
